// tools/seed/generate-zip3-centroids.ts
// One-off script: downloads the Census Bureau's 2020 Gazetteer ZCTA file,
// averages each ZCTA's centroid into its 3-digit prefix, writes
// src/data/zip3-centroids.ts. Not run as part of the app or the seed CLI —
// run manually, once, when the table needs regenerating.
import { writeFileSync } from 'fs';

// Note: the directory listing capitalizes "Gaz" — 2020_gaz_zcta_national.zip
// (lowercase) 404s.
const GAZETTEER_URL = 'https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2020_Gazetteer/2020_Gaz_zcta_national.zip';

async function main(): Promise<void> {
  console.log(`Fetching ${GAZETTEER_URL} ...`);
  console.log('This file is a zipped TSV; unzip it locally first if this script'
    + ' cannot unzip in-process, then point UNZIPPED_TSV_PATH at the .txt file below.');

  const UNZIPPED_TSV_PATH = process.env.UNZIPPED_TSV_PATH;
  if (!UNZIPPED_TSV_PATH) {
    throw new Error('Set UNZIPPED_TSV_PATH to the unzipped 2020_Gaz_zcta_national.txt file before running.');
  }
  const { readFileSync } = await import('fs');
  const lines = readFileSync(UNZIPPED_TSV_PATH, 'utf-8').split('\n').slice(1); // skip header

  const sums = new Map<string, { latSum: number; lngSum: number; count: number }>();
  for (const line of lines) {
    if (!line.trim()) continue;
    const cols = line.split('\t');
    const zcta = cols[0].trim();
    const lat = Number(cols[cols.length - 2]);
    const lng = Number(cols[cols.length - 1]);
    if (zcta.length !== 5 || Number.isNaN(lat) || Number.isNaN(lng)) continue;
    const prefix = zcta.slice(0, 3);
    const entry = sums.get(prefix) ?? { latSum: 0, lngSum: 0, count: 0 };
    entry.latSum += lat;
    entry.lngSum += lng;
    entry.count += 1;
    sums.set(prefix, entry);
  }

  const centroids: Record<string, { lat: number; lng: number }> = {};
  for (const [prefix, { latSum, lngSum, count }] of sums) {
    centroids[prefix] = { lat: Number((latSum / count).toFixed(4)), lng: Number((lngSum / count).toFixed(4)) };
  }

  const output = `// Generated by tools/seed/generate-zip3-centroids.ts from the US Census
// Bureau's 2020 Gazetteer ZCTA file. Each entry is the average centroid of
// every 5-digit ZCTA sharing that 3-digit prefix. Regenerate, don't hand-edit.
export const ZIP3_CENTROIDS: Record<string, { lat: number; lng: number }> = ${JSON.stringify(centroids, null, 2)};
`;
  writeFileSync('src/data/zip3-centroids.ts', output);
  console.log(`Wrote ${Object.keys(centroids).length} zip3 centroids to src/data/zip3-centroids.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
